apiVersion: v1
kind: Service
metadata:
  name: dev-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      name: "http"
      nodePort: 30000
      targetPort: 8080
  selector:
    app: dev-server
